-- Add import pipeline audit events
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IMPORT_PARSING_STARTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IMPORT_PARSED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IMPORT_MAPPING_SAVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IMPORT_READY';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IMPORT_ERROR';
