-- Account classification mapping and expanded check types
CREATE TYPE "AccountClass" AS ENUM (
  'EXPENSE',
  'NET_PAYABLE',
  'TAX_PAYABLE',
  'NI_PRSI_PAYABLE',
  'PENSION_PAYABLE',
  'CASH',
  'OTHER'
);

ALTER TYPE "CheckType" ADD VALUE IF NOT EXISTS 'CHK_REGISTER_DEDUCTIONS_TO_STATUTORY_TOTALS';
ALTER TYPE "CheckType" ADD VALUE IF NOT EXISTS 'CHK_REGISTER_GROSS_TO_JOURNAL_EXPENSE';
ALTER TYPE "CheckType" ADD VALUE IF NOT EXISTS 'CHK_REGISTER_EMPLOYER_COSTS_TO_JOURNAL_EXPENSE';
ALTER TYPE "CheckType" ADD VALUE IF NOT EXISTS 'CHK_REGISTER_NET_PAY_TO_JOURNAL_LIABILITY';
ALTER TYPE "CheckType" ADD VALUE IF NOT EXISTS 'CHK_REGISTER_TAX_TO_JOURNAL_LIABILITY';
ALTER TYPE "CheckType" ADD VALUE IF NOT EXISTS 'CHK_REGISTER_PENSION_TO_JOURNAL_LIABILITY';
ALTER TYPE "CheckType" ADD VALUE IF NOT EXISTS 'CHK_BANK_DUPLICATE_PAYMENTS';
ALTER TYPE "CheckType" ADD VALUE IF NOT EXISTS 'CHK_BANK_NEGATIVE_PAYMENTS';
ALTER TYPE "CheckType" ADD VALUE IF NOT EXISTS 'CHK_BANK_PAYMENT_COUNT_MISMATCH';

ALTER TYPE "ExceptionCategory" ADD VALUE IF NOT EXISTS 'BANK_DATA_QUALITY';

CREATE TABLE "AccountClassification" (
  "id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "firmId" UUID NOT NULL,
  "clientId" UUID NOT NULL,
  "accountCode" TEXT NOT NULL,
  "accountName" TEXT,
  "classification" "AccountClass" NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AccountClassification_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "AccountClassification_firmId_fkey" FOREIGN KEY ("firmId") REFERENCES "Firm"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "AccountClassification_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "AccountClassification_clientId_accountCode_key"
  ON "AccountClassification"("clientId", "accountCode");
CREATE INDEX "AccountClassification_firmId_clientId_idx"
  ON "AccountClassification"("firmId", "clientId");
